apiVersion: v1
kind: Pod
metadata:
  name: attach-pvc
spec:
  containers:
  - name: attach-pvc
    image: armandmcqueen/tensorpack-mask-rcnn:master-latest
    command: ["/bin/bash"]
    securityContext:
      privileged: true
    args: ["-c", "while true; do echo $(date -u) >> /data/out.txt; sleep 3600; done"]
    volumeMounts:
    - name:  fsx
      mountPath: /fsx
  volumes:
  - name:  fsx
    persistentVolumeClaim:
      claimName: tensorpack-fsx