apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - create
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - list
  - update
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
     app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
      - args:
        - --gpus-per-node
        - "{{ .Values.mpioperator.gpuspernode }}"
        - --kubectl-delivery-image
        - {{ .Values.mpioperator.deliveryimage }}
        image: {{ .Values.mpioperator.image }}
        imagePullPolicy: {{ .Values.mpioperator.pullpolicy }}
        name: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
      serviceAccountName: {{ .Values.mpioperator.name }}-{{ .Values.global.name }}
---